// Generated by scripts/build_data.py - do not edit by hand
window.VOCAB_DATA = [
 {
  "name": "Algebra",
  "words": [
   {
    "en": "Algebra",
    "zh": "代数"
   },
   {
    "en": "Simplify",
    "zh": "化简"
   },
   {
    "en": "Expand",
    "zh": "展开"
   },
   {
    "en": "Solve",
    "zh": "解"
   },
   {
    "en": "Unknown",
    "zh": "未知数"
   },
   {
    "en": "Variable",
    "zh": "变量"
   },
   {
    "en": "Expression",
    "zh": "表达式"
   },
   {
    "en": "Bracket",
    "zh": "括号"
   },
   {
    "en": "Equation",
    "zh": "等式，方程"
   },
   {
    "en": "Term",
    "zh": "项"
   },
   {
    "en": "Double",
    "zh": "二倍"
   },
   {
    "en": "Triple",
    "zh": "三倍"
   },
   {
    "en": "Quadruple",
    "zh": "四倍"
   },
   {
    "en": "Like term",
    "zh": "同类项"
   },
   {
    "en": "Coefficient",
    "zh": "系数"
   },
   {
    "en": "Constant",
    "zh": "常数"
   },
   {
    "en": "Power, exponent, index",
    "zh": "指数，幂"
   },
   {
    "en": "Quantity",
    "zh": "量"
   },
   {
    "en": "Consecutive",
    "zh": "连续的"
   },
   {
    "en": "Quotient",
    "zh": "商"
   },
   {
    "en": "Remainder",
    "zh": "余数"
   },
   {
    "en": "Difference",
    "zh": "差"
   },
   {
    "en": "Dividend",
    "zh": "被除数"
   },
   {
    "en": "Divisor",
    "zh": "除数"
   },
   {
    "en": "Less than",
    "zh": "小于"
   },
   {
    "en": "Greater than",
    "zh": "大于"
   },
   {
    "en": "Less than or equal to",
    "zh": "小于等于"
   },
   {
    "en": "Greater than or equal to",
    "zh": "大于等于"
   },
   {
    "en": "Reciprocal",
    "zh": "倒数"
   },
   {
    "en": "Square root",
    "zh": "平方根"
   },
   {
    "en": "Solve equations",
    "zh": "解方程"
   },
   {
    "en": "Index, indices",
    "zh": "指数"
   },
   {
    "en": "Inequality",
    "zh": "不等式"
   },
   {
    "en": "Number line",
    "zh": "数轴"
   },
   {
    "en": "Solution",
    "zh": "方程的解"
   },
   {
    "en": "Root",
    "zh": "方程的根"
   },
   {
    "en": "Factorise",
    "zh": "因式分解"
   },
   {
    "en": "Common factor",
    "zh": "公因数，公因式"
   },
   {
    "en": "Algebraic fraction",
    "zh": "代数分数"
   },
   {
    "en": "Lowest common denominator",
    "zh": "最小公分母"
   },
   {
    "en": "Simultaneous equations",
    "zh": "联立方程，方程组"
   },
   {
    "en": "Substitution",
    "zh": "代入法"
   },
   {
    "en": "Elimination",
    "zh": "消元法"
   },
   {
    "en": "Formula, formulae",
    "zh": "公式"
   },
   {
    "en": "Make… the subject",
    "zh": "把…作为计算对象"
   },
   {
    "en": "Function",
    "zh": "函数"
   },
   {
    "en": "Mapping diagram",
    "zh": "映射图"
   },
   {
    "en": "Domain",
    "zh": "定义域"
   },
   {
    "en": "Range",
    "zh": "值域"
   },
   {
    "en": "Composite function",
    "zh": "复合函数"
   },
   {
    "en": "Inverse function",
    "zh": "反函数"
   },
   {
    "en": "Directly proportional",
    "zh": "正比"
   },
   {
    "en": "Inversely proportional",
    "zh": "反比"
   },
   {
    "en": "Quadratic equation",
    "zh": "二次方程"
   },
   {
    "en": "Complete the square",
    "zh": "配方"
   },
   {
    "en": "Counter-example",
    "zh": "反例"
   },
   {
    "en": "Statement",
    "zh": "陈述"
   },
   {
    "en": "Even",
    "zh": "偶数"
   },
   {
    "en": "Odd",
    "zh": "奇数"
   }
  ]
 },
 {
  "name": "Graph",
  "words": [
   {
    "en": "Gradient, slope",
    "zh": "斜率"
   },
   {
    "en": "Intercept",
    "zh": "截距"
   },
   {
    "en": "Plot",
    "zh": "描点"
   },
   {
    "en": "Point",
    "zh": "点"
   },
   {
    "en": "Origin",
    "zh": "原点"
   },
   {
    "en": "Axis, axes",
    "zh": "轴"
   },
   {
    "en": "Vertical",
    "zh": "垂直的"
   },
   {
    "en": "Horizontal",
    "zh": "水平的"
   },
   {
    "en": "Coordinate",
    "zh": "坐标"
   },
   {
    "en": "Positive",
    "zh": "正的"
   },
   {
    "en": "Negative",
    "zh": "负的"
   },
   {
    "en": "Quadrant",
    "zh": "象限"
   },
   {
    "en": "Scale factor",
    "zh": "比例因子"
   },
   {
    "en": "Maximum",
    "zh": "最大值"
   },
   {
    "en": "Minimum",
    "zh": "最小值"
   },
   {
    "en": "Linear",
    "zh": "线性的"
   },
   {
    "en": "Function",
    "zh": "函数"
   },
   {
    "en": "Variable",
    "zh": "变量"
   },
   {
    "en": "Rate",
    "zh": "变化率"
   },
   {
    "en": "Uniform",
    "zh": "均匀地"
   },
   {
    "en": "Replace",
    "zh": "替换"
   },
   {
    "en": "Substitute",
    "zh": "代入"
   },
   {
    "en": "Against",
    "zh": "…关于…"
   },
   {
    "en": "Exact",
    "zh": "精确的"
   },
   {
    "en": "Converse",
    "zh": "转换"
   },
   {
    "en": "Equivalent",
    "zh": "等价的"
   },
   {
    "en": "Gallon",
    "zh": "加仑"
   },
   {
    "en": "Mile per hour (mph)",
    "zh": "英里每小时"
   },
   {
    "en": "Foot, feet",
    "zh": "英尺"
   },
   {
    "en": "Fahrenheit",
    "zh": "华氏度"
   },
   {
    "en": "Celsius",
    "zh": "摄氏度"
   },
   {
    "en": "Rearrange",
    "zh": "重新排列"
   },
   {
    "en": "Infinite",
    "zh": "无限的"
   },
   {
    "en": "Hundreds",
    "zh": "以百计数"
   },
   {
    "en": "Thousands",
    "zh": "以千计数"
   },
   {
    "en": "Millions",
    "zh": "以百万计数"
   },
   {
    "en": "Sketch",
    "zh": "画草图"
   },
   {
    "en": "Intersection",
    "zh": "交点"
   },
   {
    "en": "Distance",
    "zh": "距离"
   },
   {
    "en": "Displacement",
    "zh": "位移"
   },
   {
    "en": "Constant speed",
    "zh": "匀速"
   },
   {
    "en": "Increasing speed",
    "zh": "加速"
   },
   {
    "en": "Decreasing speed",
    "zh": "减速"
   },
   {
    "en": "Average speed",
    "zh": "平均速度"
   },
   {
    "en": "Instantaneous speed",
    "zh": "瞬时速度"
   },
   {
    "en": "Velocity",
    "zh": "速度"
   },
   {
    "en": "Movement",
    "zh": "运动"
   },
   {
    "en": "Acceleration",
    "zh": "加速度"
   },
   {
    "en": "Deceleration",
    "zh": "减速度"
   },
   {
    "en": "Retardation",
    "zh": "减速度"
   },
   {
    "en": "Straight line",
    "zh": "直线"
   },
   {
    "en": "Curve",
    "zh": "曲线"
   },
   {
    "en": "Quadratic graph",
    "zh": "二次图像"
   },
   {
    "en": "Parabola",
    "zh": "抛物线"
   },
   {
    "en": "Dimension",
    "zh": "维度，大小"
   },
   {
    "en": "Cubic graph",
    "zh": "三次函数"
   },
   {
    "en": "Reciprocal function",
    "zh": "倒数函数"
   },
   {
    "en": "Hyperbola",
    "zh": "双曲线"
   },
   {
    "en": "Asymptote",
    "zh": "渐近线"
   },
   {
    "en": "Column vector",
    "zh": "列向量"
   },
   {
    "en": "Tangent",
    "zh": "切线"
   },
   {
    "en": "Transformation",
    "zh": "变换"
   },
   {
    "en": "Translation",
    "zh": "平移"
   },
   {
    "en": "Reflection",
    "zh": "映射"
   },
   {
    "en": "Stretch",
    "zh": "拉伸"
   },
   {
    "en": "Compress",
    "zh": "压缩"
   },
   {
    "en": "Differentiation",
    "zh": "微分，求导"
   },
   {
    "en": "Gradient function",
    "zh": "斜率函数，梯度函数"
   },
   {
    "en": "Derivative",
    "zh": "求导"
   },
   {
    "en": "Equation of the tangent",
    "zh": "切线方程"
   },
   {
    "en": "Rate of change",
    "zh": "变化率"
   }
  ]
 },
 {
  "name": "Handling data",
  "words": [
   {
    "en": "Statistics",
    "zh": "统计"
   },
   {
    "en": "Collect data",
    "zh": "收集数据"
   },
   {
    "en": "Category",
    "zh": "类别"
   },
   {
    "en": "Tally chart",
    "zh": "统计表"
   },
   {
    "en": "Pie chart",
    "zh": "饼图"
   },
   {
    "en": "Bar chart",
    "zh": "柱状图"
   },
   {
    "en": "Pictogram",
    "zh": "象形图"
   },
   {
    "en": "Mean",
    "zh": "算术平均数"
   },
   {
    "en": "Median",
    "zh": "中位数"
   },
   {
    "en": "Mode",
    "zh": "众数"
   },
   {
    "en": "Average",
    "zh": "平均数"
   },
   {
    "en": "Ascending",
    "zh": "升幂"
   },
   {
    "en": "Frequency",
    "zh": "频率"
   },
   {
    "en": "Sample",
    "zh": "样本"
   },
   {
    "en": "Pattern",
    "zh": "规律，模式"
   },
   {
    "en": "Trend",
    "zh": "趋势"
   },
   {
    "en": "Analyse",
    "zh": "分析"
   },
   {
    "en": "Predictions",
    "zh": "预测"
   },
   {
    "en": "Numeric data",
    "zh": "数值数据"
   },
   {
    "en": "Categorical data",
    "zh": "非数值数据，类别数据"
   },
   {
    "en": "Discrete",
    "zh": "离散的"
   },
   {
    "en": "Continuous",
    "zh": "连续的"
   },
   {
    "en": "Range",
    "zh": "极差"
   },
   {
    "en": "Classify",
    "zh": "分类"
   },
   {
    "en": "Count",
    "zh": "计数"
   },
   {
    "en": "Measure",
    "zh": "测量"
   },
   {
    "en": "Distribution",
    "zh": "分布"
   },
   {
    "en": "Comment",
    "zh": "评论"
   },
   {
    "en": "Random",
    "zh": "随机"
   },
   {
    "en": "Proportion",
    "zh": "比例"
   },
   {
    "en": "Survey",
    "zh": "调查"
   },
   {
    "en": "Comparative",
    "zh": "比较的"
   },
   {
    "en": "Misleading",
    "zh": "令人误解的"
   },
   {
    "en": "Outlier",
    "zh": "异常值"
   },
   {
    "en": "Extreme value",
    "zh": "极值"
   },
   {
    "en": "Estimate",
    "zh": "估算"
   },
   {
    "en": "Grouped frequency table",
    "zh": "分组频率表"
   },
   {
    "en": "Modal class",
    "zh": "众数组"
   },
   {
    "en": "Sigma",
    "zh": "求和符号"
   },
   {
    "en": "Cumulative frequency",
    "zh": "累计频率"
   },
   {
    "en": "Class",
    "zh": "组"
   },
   {
    "en": "Frequency polygon",
    "zh": "频数多边形"
   },
   {
    "en": "Dispersion, spread",
    "zh": "离散，散布"
   },
   {
    "en": "Upper quartile",
    "zh": "上四分位"
   },
   {
    "en": "Lower quartile",
    "zh": "下四分位"
   },
   {
    "en": "Percentile",
    "zh": "百分位"
   },
   {
    "en": "Inter-quartile range",
    "zh": "四分位差"
   },
   {
    "en": "Box plot",
    "zh": "箱型图"
   },
   {
    "en": "Occur",
    "zh": "发生"
   },
   {
    "en": "Probability",
    "zh": "概率"
   },
   {
    "en": "Sample space",
    "zh": "样本空间"
   },
   {
    "en": "Probability space",
    "zh": "概率空间"
   },
   {
    "en": "Possible",
    "zh": "可能的"
   },
   {
    "en": "Outcome",
    "zh": "结果"
   },
   {
    "en": "Mutually exclusive events",
    "zh": "互斥事件"
   },
   {
    "en": "Expected frequency",
    "zh": "期望频数"
   },
   {
    "en": "Experimental probability",
    "zh": "实验概率"
   },
   {
    "en": "Theoretical probability",
    "zh": "理论概率"
   },
   {
    "en": "Trial",
    "zh": "试验"
   },
   {
    "en": "Relative frequency",
    "zh": "相对频率"
   },
   {
    "en": "Die",
    "zh": "骰子"
   },
   {
    "en": "Heart",
    "zh": "桃心"
   },
   {
    "en": "Diamond",
    "zh": "方块"
   },
   {
    "en": "Spade",
    "zh": "黑桃"
   },
   {
    "en": "Club",
    "zh": "草花"
   },
   {
    "en": "Spinner",
    "zh": "陀螺"
   },
   {
    "en": "Equally likely",
    "zh": "等可能的"
   },
   {
    "en": "Independent events",
    "zh": "独立事件"
   },
   {
    "en": "Dependent events",
    "zh": "相关事件"
   },
   {
    "en": "Tree diagram",
    "zh": "树状图"
   },
   {
    "en": "Conditional probability",
    "zh": "条件概率"
   },
   {
    "en": "Histogram",
    "zh": "直方图"
   },
   {
    "en": "Frequency density",
    "zh": "频率密度"
   },
   {
    "en": "Class width",
    "zh": "组宽"
   }
  ]
 },
 {
  "name": "Number",
  "words": [
   {
    "en": "Decimal",
    "zh": "小数"
   },
   {
    "en": "Terminating decimal",
    "zh": "有尽小数"
   },
   {
    "en": "Recurring decimal",
    "zh": "循环小数"
   },
   {
    "en": "Percentage",
    "zh": "百分比"
   },
   {
    "en": "Average",
    "zh": "平均数"
   },
   {
    "en": "Convert",
    "zh": "转换"
   },
   {
    "en": "Whole number",
    "zh": "整数"
   },
   {
    "en": "Quarter",
    "zh": "四分之一"
   },
   {
    "en": "Equal",
    "zh": "相等"
   },
   {
    "en": "Reciprocal",
    "zh": "倒数"
   },
   {
    "en": "Identical",
    "zh": "一致的"
   },
   {
    "en": "Index, indices",
    "zh": "指数"
   },
   {
    "en": "Digit",
    "zh": "数位"
   },
   {
    "en": "Count",
    "zh": "计数"
   },
   {
    "en": "Round up",
    "zh": "五入"
   },
   {
    "en": "Prime number",
    "zh": "质数"
   },
   {
    "en": "Sign",
    "zh": "符号"
   },
   {
    "en": "Add, plus",
    "zh": "加"
   },
   {
    "en": "Subtract, minus",
    "zh": "减"
   },
   {
    "en": "Multiply, time",
    "zh": "乘"
   },
   {
    "en": "Divide",
    "zh": "除"
   },
   {
    "en": "Fraction",
    "zh": "分数"
   },
   {
    "en": "Least common multiple",
    "zh": "最小公倍数"
   },
   {
    "en": "Highest common factor",
    "zh": "最大公因数"
   },
   {
    "en": "Proper fraction",
    "zh": "真分数"
   },
   {
    "en": "Improper fraction",
    "zh": "假分数"
   },
   {
    "en": "Mixed number",
    "zh": "带分数"
   },
   {
    "en": "Numerator",
    "zh": "分子"
   },
   {
    "en": "Simplify",
    "zh": "化简"
   },
   {
    "en": "Evaluate",
    "zh": "求…的值"
   },
   {
    "en": "Calculate",
    "zh": "计算"
   },
   {
    "en": "Bracket",
    "zh": "括号"
   },
   {
    "en": "Order of operations",
    "zh": "运算顺序"
   },
   {
    "en": "Significant figures",
    "zh": "有效数字"
   },
   {
    "en": "Decimal places",
    "zh": "小数位"
   },
   {
    "en": "Round to",
    "zh": "四舍五入"
   },
   {
    "en": "Correct to",
    "zh": "精确到"
   },
   {
    "en": "Degree of accuracy",
    "zh": "精确度"
   },
   {
    "en": "Real number",
    "zh": "实数"
   },
   {
    "en": "Rational number",
    "zh": "有理数"
   },
   {
    "en": "Irrational number",
    "zh": "无理数"
   },
   {
    "en": "Natural number",
    "zh": "自然数"
   },
   {
    "en": "Integer",
    "zh": "整数"
   },
   {
    "en": "Approximate",
    "zh": "近似的"
   },
   {
    "en": "Exact value",
    "zh": "精确值"
   },
   {
    "en": "Standard form",
    "zh": "科学计数法"
   },
   {
    "en": "Ordinary number",
    "zh": "普通数字"
   },
   {
    "en": "Positive",
    "zh": "正数"
   },
   {
    "en": "Negative",
    "zh": "负数"
   },
   {
    "en": "Mile",
    "zh": "英里"
   },
   {
    "en": "Foot, feet",
    "zh": "英尺"
   },
   {
    "en": "Inch, inches",
    "zh": "英寸"
   },
   {
    "en": "Power",
    "zh": "幂"
   },
   {
    "en": "To the nearest …",
    "zh": "近似到…"
   },
   {
    "en": "Hundred",
    "zh": "百位"
   },
   {
    "en": "Thousand",
    "zh": "千位"
   },
   {
    "en": "Hundredth",
    "zh": "百分位"
   },
   {
    "en": "Thousandth",
    "zh": "千分位"
   },
   {
    "en": "Cube",
    "zh": "立方"
   },
   {
    "en": "Circumference",
    "zh": "圆的周长"
   },
   {
    "en": "Ratio",
    "zh": "比值"
   },
   {
    "en": "Proportion",
    "zh": "比例"
   },
   {
    "en": "Percent",
    "zh": "百分之…"
   },
   {
    "en": "scale factor",
    "zh": "比例因子"
   },
   {
    "en": "Original price",
    "zh": "原价"
   },
   {
    "en": "Appreciate",
    "zh": "增值"
   },
   {
    "en": "Depreciate",
    "zh": "贬值"
   },
   {
    "en": "Gain",
    "zh": "获得"
   },
   {
    "en": "Increase",
    "zh": "增加"
   },
   {
    "en": "Lose",
    "zh": "失去"
   },
   {
    "en": "Reduce",
    "zh": "减少"
   },
   {
    "en": "Decrease",
    "zh": "减少"
   },
   {
    "en": "Per annum (p.a.)",
    "zh": "每年"
   },
   {
    "en": "Multiple",
    "zh": "倍数"
   },
   {
    "en": "Factor",
    "zh": "因数"
   },
   {
    "en": "Infinite",
    "zh": "无穷的"
   },
   {
    "en": "Prime factor",
    "zh": "质因数"
   },
   {
    "en": "Uniquely",
    "zh": "唯一的"
   },
   {
    "en": "Product",
    "zh": "乘积"
   },
   {
    "en": "Index form",
    "zh": "指数形式"
   },
   {
    "en": "Simple interest",
    "zh": "单利"
   },
   {
    "en": "Compound interest",
    "zh": "复利"
   },
   {
    "en": "Inflation",
    "zh": "通货膨胀"
   },
   {
    "en": "Deflation",
    "zh": "通货紧缩"
   },
   {
    "en": "Metric unit",
    "zh": "公制单位"
   },
   {
    "en": "Length",
    "zh": "长度"
   },
   {
    "en": "Meter",
    "zh": "米"
   },
   {
    "en": "Kilometer",
    "zh": "千米"
   },
   {
    "en": "Centimeter",
    "zh": "厘米"
   },
   {
    "en": "Millimeter",
    "zh": "毫米"
   },
   {
    "en": "Volume",
    "zh": "体积"
   },
   {
    "en": "Litre",
    "zh": "升"
   },
   {
    "en": "Millilitre",
    "zh": "毫升"
   },
   {
    "en": "Gram",
    "zh": "克"
   },
   {
    "en": "Kilogram",
    "zh": "千克"
   },
   {
    "en": "Tonne",
    "zh": "吨"
   },
   {
    "en": "Speed",
    "zh": "速率，速度"
   },
   {
    "en": "Density",
    "zh": "密度"
   },
   {
    "en": "Pressure",
    "zh": "压强，压力"
   },
   {
    "en": "Force",
    "zh": "力"
   },
   {
    "en": "Mass",
    "zh": "质量"
   },
   {
    "en": "Dollar",
    "zh": "美元"
   },
   {
    "en": "Cent",
    "zh": "美分"
   },
   {
    "en": "Pound",
    "zh": "英镑"
   },
   {
    "en": "Penny, pence",
    "zh": "便士"
   },
   {
    "en": "Salary",
    "zh": "薪水"
   },
   {
    "en": "Income tax",
    "zh": "个税"
   },
   {
    "en": "Sales tax",
    "zh": "消费税"
   },
   {
    "en": "Currency",
    "zh": "货币"
   },
   {
    "en": "Surd",
    "zh": "根数，无理数"
   },
   {
    "en": "Perfect square",
    "zh": "完全平方"
   },
   {
    "en": "Square root",
    "zh": "平方根"
   },
   {
    "en": "Rationalise the denominator",
    "zh": "分母有理化"
   }
  ]
 },
 {
  "name": "Sequence",
  "words": [
   {
    "en": "Sequence",
    "zh": "数列"
   },
   {
    "en": "Pattern",
    "zh": "规律，模式"
   },
   {
    "en": "Term",
    "zh": "项"
   },
   {
    "en": "Add",
    "zh": "加"
   },
   {
    "en": "Subtract",
    "zh": "减"
   },
   {
    "en": "Multiply",
    "zh": "乘"
   },
   {
    "en": "Divide",
    "zh": "除"
   },
   {
    "en": "Consecutive",
    "zh": "连续的"
   },
   {
    "en": "Common difference",
    "zh": "公差"
   },
   {
    "en": "Arithmetic sequence",
    "zh": "等差数列"
   },
   {
    "en": "Arithmetic series",
    "zh": "等差级数"
   }
  ]
 },
 {
  "name": "Set",
  "words": [
   {
    "en": "Argument",
    "zh": "论据"
   },
   {
    "en": "Set",
    "zh": "数集"
   },
   {
    "en": "Venn diagram",
    "zh": "韦恩图"
   },
   {
    "en": "Odd",
    "zh": "奇数"
   },
   {
    "en": "Even",
    "zh": "偶数"
   },
   {
    "en": "Prime",
    "zh": "质数"
   },
   {
    "en": "Square number",
    "zh": "平方数"
   },
   {
    "en": "Multiple",
    "zh": "倍数"
   },
   {
    "en": "Factor",
    "zh": "因数"
   },
   {
    "en": "Element, member",
    "zh": "元素"
   },
   {
    "en": "Infinite",
    "zh": "无限的"
   },
   {
    "en": "Finite",
    "zh": "有限的"
   },
   {
    "en": "Integer",
    "zh": "整数"
   },
   {
    "en": "Power",
    "zh": "幂"
   },
   {
    "en": "Digit",
    "zh": "数位"
   },
   {
    "en": "Subset",
    "zh": "子集"
   },
   {
    "en": "Empty set",
    "zh": "空集"
   },
   {
    "en": "Universal set",
    "zh": "全集"
   },
   {
    "en": "Complement",
    "zh": "补集"
   },
   {
    "en": "Intersection",
    "zh": "交集"
   },
   {
    "en": "Union",
    "zh": "并集"
   },
   {
    "en": "Overlap",
    "zh": "重叠"
   }
  ]
 },
 {
  "name": "Shape and space",
  "words": [
   {
    "en": "Angle",
    "zh": "角"
   },
   {
    "en": "Side",
    "zh": "边"
   },
   {
    "en": "Straight line",
    "zh": "直线"
   },
   {
    "en": "Vertical",
    "zh": "垂直的"
   },
   {
    "en": "Horizontal",
    "zh": "水平的"
   },
   {
    "en": "Opposite angle",
    "zh": "对顶角"
   },
   {
    "en": "Alternate angle",
    "zh": "内错角"
   },
   {
    "en": "Corresponding angle",
    "zh": "同位角"
   },
   {
    "en": "Co-interior angles",
    "zh": "同旁内角"
   },
   {
    "en": "Line of symmetry",
    "zh": "对称轴"
   },
   {
    "en": "Fold",
    "zh": "折叠"
   },
   {
    "en": "Rotational symmetry",
    "zh": "旋转对称"
   },
   {
    "en": "Symmetry of order...",
    "zh": "…阶对称"
   },
   {
    "en": "Isosceles triangle",
    "zh": "等腰三角形"
   },
   {
    "en": "Equilateral triangle",
    "zh": "等边三角形"
   },
   {
    "en": "Interior angle",
    "zh": "内角"
   },
   {
    "en": "Exterior angle",
    "zh": "外角"
   },
   {
    "en": "Clockwise",
    "zh": "顺时针"
   },
   {
    "en": "Anti-clockwise",
    "zh": "逆时针"
   },
   {
    "en": "Mid-point",
    "zh": "中点"
   },
   {
    "en": "Right angle",
    "zh": "直角"
   },
   {
    "en": "Acute angle",
    "zh": "锐角"
   },
   {
    "en": "Obtuse angle",
    "zh": "钝角"
   },
   {
    "en": "Reflex angle",
    "zh": "优角"
   },
   {
    "en": "Pythagoras’ theorem",
    "zh": "勾股定理"
   },
   {
    "en": "Trigonometry",
    "zh": "三角学"
   },
   {
    "en": "Quadrilateral",
    "zh": "四边形"
   },
   {
    "en": "Square",
    "zh": "正方形"
   },
   {
    "en": "Rectangle",
    "zh": "矩形"
   },
   {
    "en": "Kite",
    "zh": "筝形"
   },
   {
    "en": "Rhombus",
    "zh": "菱形"
   },
   {
    "en": "Parallelogram",
    "zh": "平行四边形"
   },
   {
    "en": "Trapezium",
    "zh": "梯形"
   },
   {
    "en": "Extend",
    "zh": "延长"
   },
   {
    "en": "Meet, intersect",
    "zh": "相交"
   },
   {
    "en": "Perpendicular",
    "zh": "垂直"
   },
   {
    "en": "Diagonal",
    "zh": "对角线"
   },
   {
    "en": "Polygon",
    "zh": "多边形"
   },
   {
    "en": "Pentagon",
    "zh": "五边形"
   },
   {
    "en": "Hexagon",
    "zh": "六边形"
   },
   {
    "en": "Heptagon",
    "zh": "七边形"
   },
   {
    "en": "Octagon",
    "zh": "八边形"
   },
   {
    "en": "Regular polygon",
    "zh": "正多边形"
   },
   {
    "en": "Construct",
    "zh": "构建"
   },
   {
    "en": "Compass",
    "zh": "圆规"
   },
   {
    "en": "Bearing",
    "zh": "方位"
   },
   {
    "en": "Scale factor",
    "zh": "比例因子"
   },
   {
    "en": "Reduce",
    "zh": "减少"
   },
   {
    "en": "Enlarge",
    "zh": "放大"
   },
   {
    "en": "Arc",
    "zh": "弧"
   },
   {
    "en": "Intersection",
    "zh": "交点"
   },
   {
    "en": "Protractor",
    "zh": "量角器"
   },
   {
    "en": "Tetrahedron",
    "zh": "四面体"
   },
   {
    "en": "Segment",
    "zh": "线段，部分"
   },
   {
    "en": "Bisector",
    "zh": "平分线"
   },
   {
    "en": "Equidistant",
    "zh": "等距"
   },
   {
    "en": "Vertex, vertices",
    "zh": "顶点"
   },
   {
    "en": "Congruent triangle",
    "zh": "全等三角形"
   },
   {
    "en": "Similar Triangle",
    "zh": "相似三角形"
   },
   {
    "en": "Ratio",
    "zh": "比率"
   },
   {
    "en": "Tangent",
    "zh": "切线"
   },
   {
    "en": "Chord",
    "zh": "圆上的弦"
   },
   {
    "en": "Diameter",
    "zh": "直径"
   },
   {
    "en": "Radius",
    "zh": "半径"
   },
   {
    "en": "Circumference",
    "zh": "圆的周长"
   },
   {
    "en": "Centre of a circle",
    "zh": "圆心"
   },
   {
    "en": "Due east/south/west/north",
    "zh": "向东南西北"
   },
   {
    "en": "Cross-section",
    "zh": "横截面"
   },
   {
    "en": "Sine",
    "zh": "正弦"
   },
   {
    "en": "Cosine",
    "zh": "余弦"
   },
   {
    "en": "Tangent",
    "zh": "正切"
   },
   {
    "en": "Hypotenuse",
    "zh": "斜边"
   },
   {
    "en": "Opposite",
    "zh": "对边"
   },
   {
    "en": "Adjacent",
    "zh": "邻边"
   },
   {
    "en": "Angle of elevation",
    "zh": "仰角"
   },
   {
    "en": "Angle of depression",
    "zh": "俯角"
   },
   {
    "en": "Degree",
    "zh": "度数"
   },
   {
    "en": "Inverse trigonometric function",
    "zh": "反三角函数"
   },
   {
    "en": "Transformation",
    "zh": "变换"
   },
   {
    "en": "Translation",
    "zh": "平移"
   },
   {
    "en": "Reflection",
    "zh": "映射"
   },
   {
    "en": "Rotation",
    "zh": "旋转"
   },
   {
    "en": "Enlargement",
    "zh": "放大"
   },
   {
    "en": "Flip",
    "zh": "翻转"
   },
   {
    "en": "Orientation",
    "zh": "方向"
   },
   {
    "en": "Map",
    "zh": "映射"
   },
   {
    "en": "Successive transformation",
    "zh": "连续变换"
   },
   {
    "en": "Perimeter",
    "zh": "周长"
   },
   {
    "en": "Circumference",
    "zh": "圆的周长"
   },
   {
    "en": "Semicircle",
    "zh": "半圆"
   },
   {
    "en": "Quadrant",
    "zh": "四分之一圆"
   },
   {
    "en": "Arc",
    "zh": "弧"
   },
   {
    "en": "Sector",
    "zh": "扇形"
   },
   {
    "en": "Solid",
    "zh": "立体"
   },
   {
    "en": "Volume",
    "zh": "体积"
   },
   {
    "en": "Prism",
    "zh": "棱柱体"
   },
   {
    "en": "Cylinder",
    "zh": "圆柱体"
   },
   {
    "en": "Cuboid",
    "zh": "长方体"
   },
   {
    "en": "Pyramid",
    "zh": "角锥体"
   },
   {
    "en": "Cone",
    "zh": "圆锥体"
   },
   {
    "en": "Sphere",
    "zh": "球体"
   },
   {
    "en": "Vector",
    "zh": "向量"
   },
   {
    "en": "Scalar",
    "zh": "标量"
   },
   {
    "en": "Magnitude",
    "zh": "大小，长度"
   },
   {
    "en": "Resultant vector",
    "zh": "复合向量"
   },
   {
    "en": "Collinear",
    "zh": "共线"
   }
  ]
 }
];
window.STUDENT_DATA = [
 {
  "name": "Kevin Chen",
  "cn": "陈沐恩",
  "score": 7
 },
 {
  "name": "Freya Fang",
  "cn": "方林熠伽",
  "score": 29
 },
 {
  "name": "Kane Huang",
  "cn": "黄凯博",
  "score": 22
 },
 {
  "name": "Kevin Jiang",
  "cn": "姜佶乐",
  "score": 8
 },
 {
  "name": "Eleanor Li",
  "cn": "李星瑶",
  "score": 38
 },
 {
  "name": "Joan Luo",
  "cn": "骆钰涵",
  "score": 6
 },
 {
  "name": "Mona Mao",
  "cn": "毛一涵",
  "score": 30
 },
 {
  "name": "Jimi Mu",
  "cn": "穆彦廷",
  "score": 0
 },
 {
  "name": "Andrew Shen",
  "cn": "沈翀旭",
  "score": 24
 },
 {
  "name": "Leo Shen",
  "cn": "沈俊梁",
  "score": null
 },
 {
  "name": "Olivia Shu",
  "cn": "舒意然",
  "score": 21
 },
 {
  "name": "Tony Wang",
  "cn": "王皓宇",
  "score": 15
 },
 {
  "name": "Alice Wang",
  "cn": "王馨",
  "score": 23
 },
 {
  "name": "Judy Wu",
  "cn": "吴雨墨",
  "score": 11
 },
 {
  "name": "Zane Xu",
  "cn": "徐正",
  "score": 3
 },
 {
  "name": "April Yang",
  "cn": "杨妍彤",
  "score": 7
 },
 {
  "name": "Angelina Ye",
  "cn": "叶如意",
  "score": 15
 },
 {
  "name": "Jessica Zhang",
  "cn": "张绮文",
  "score": 5
 },
 {
  "name": "Lawrence Zhang",
  "cn": "章若瀚",
  "score": 31
 },
 {
  "name": "Aria Zheng",
  "cn": "郑冰妍",
  "score": 25
 },
 {
  "name": "Freya Zheng",
  "cn": "郑诗诺",
  "score": 14
 }
];
