"""Regenerate data.js from the docx word lists and the class score sheet.

Usage:  python scripts/build_data.py
English name, Chinese name and quiz score are exported (no student IDs).
"""
import glob, json, re, os
import docx, openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

topics = []
for f in sorted(glob.glob("Vocabulary Test - * - Answer.docx")):
    name = re.sub(r"Vocabulary Test - (.*) - Answer\.docx", r"\1", f)
    d = docx.Document(f)
    words = []
    for t in d.tables:
        for r in t.rows:
            en = r.cells[0].text.strip().rstrip(",").strip()
            zh = r.cells[1].text.strip()
            if en and zh:
                words.append({"en": en, "zh": zh})
    topics.append({"name": name, "words": words})
    print(f"{name}: {len(words)} words")

students = []
xlsx = glob.glob("*.xlsx")
if xlsx:
    wb = openpyxl.load_workbook(xlsx[0])
    ws = wb["test"] if "test" in wb.sheetnames else wb.active
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row[0] or str(row[0]).lower() == "average":
            continue
        name = str(row[2]).replace("‌", "").strip()
        score = row[9] if isinstance(row[9], (int, float)) else None
        students.append({"name": name, "cn": str(row[1] or "").strip(), "score": score})
    print(f"{len(students)} students")

with open("data.js", "w", encoding="utf-8") as fh:
    fh.write("// Generated by scripts/build_data.py - do not edit by hand\n")
    fh.write("window.VOCAB_DATA = " + json.dumps(topics, ensure_ascii=False, indent=1) + ";\n")
    fh.write("window.STUDENT_DATA = " + json.dumps(students, ensure_ascii=False, indent=1) + ";\n")
print("wrote data.js")
